### ISSUE TITLE
Installing as a service fails on first try

### ISSUE THREAD

**Issue by enys** [Linkurious/pattypm#13]
Running  sudo /opt/linkurious/menu.sh install --user=appuser_linkur for the first time produces :
 Linkurious Manager error: Cannot install as a service: the process owner must be set
Running a second time it works fine.

This is due to the fact that service templates are created in the ctor :https://github.com/Linkurious/pattypm/blob/develop/src/Patty.js#L76

But variables are passed in later.

**Comment by davidrapin** [comment]
not shipped yet

**Comment by davidrapin** [comment]
fixed
